import type {
  ProductDefinition,
  ProductModuleManifest
} from "../product/index.js";

type TodoProductDefinition = ProductModuleManifest &
  ProductDefinition & {
    chrome: {
      errorHeading: string;
      loadingLabel: string;
      metadataDescription: string;
      metadataTitle: string;
    };
    workspaceSettings: {
      planUsage: {
        emptyStateDescription: string;
        metrics: {
          currentPlan: string;
          includedUnits: string;
          remainingUnits: string;
          usedThisMonth: string;
        };
        navDescription: string;
        navLabel: string;
        noPermissionDescription: string;
        resetDatePrefix: string;
        sectionDescription: string;
        sectionTitle: string;
        selectedPlanSuffix: string;
        switchToPlanPrefix: string;
        usageWindowPrefix: string;
      };
    };
  };

export const todoProduct = {
  "capabilities": [
    {
      "description": "Provides the Todo product shell.",
      "id": "todo-ui",
      "kind": "ui"
    },
    {
      "description": "Provides the Todo workspace navigation.",
      "id": "todo-navigation",
      "kind": "navigation"
    },
    {
      "description": "Provides the todos resource slice.",
      "id": "todo-todo",
      "kind": "resource"
    }
  ],
  "chrome": {
    "errorHeading": "Unable to load Todo",
    "loadingLabel": "Loading Todo...",
    "metadataDescription": "Todo is a simple resource-backed workspace product generated by Elioric.",
    "metadataTitle": "Todo"
  },
  "description": "Todo is a simple resource-backed workspace product generated by Elioric.",
  "emptyStateCopy": {
    "emptyStateDescription": "Track work through one generated todo resource without hand-editing product runtime seams.",
    "emptyStateTitle": "Todo workspace",
    "primaryCtaHref": "/todo",
    "primaryCtaLabel": "Open Todos"
  },
  "id": "todo",
  "name": "Todo",
  "navItems": [
    {
      "href": "/todo",
      "id": "todo-home",
      "label": "Todo"
    },
    {
      "href": "/todo/todos",
      "id": "todo-todos",
      "label": "Todos"
    }
  ],
  "onboardingContent": {
    "completeSummaryDescription": "Todo setup is complete.",
    "dismissFromSidebarLabel": "Dismiss from sidebar",
    "eyebrow": "Todo setup",
    "incompleteSummaryDescription": "Todo does not require additional setup for the initial generated proof.",
    "showInSidebarLabel": "Show in sidebar",
    "stepContent": [],
    "title": "Todo getting started"
  },
  "onboardingSteps": [],
  "resources": [
    {
      "id": "todo",
      "navigationId": "todo-todos",
      "ownership": "organization",
      "routeBasePath": "/todo/todos"
    }
  ],
  "runtime": {
    "registrations": []
  },
  "usageMeters": [
    {
      "key": "todo",
      "label": "Todo"
    }
  ],
  "workspaceSettings": {
    "planUsage": {
      "emptyStateDescription": "Todo usage will appear here once product-specific limits are added.",
      "metrics": {
        "currentPlan": "Current plan",
        "includedUnits": "Included todos",
        "remainingUnits": "Remaining todos",
        "usedThisMonth": "Created this month"
      },
      "navDescription": "Track how Todo will use your workspace plan.",
      "navLabel": "Todo usage",
      "noPermissionDescription": "You do not have permission to inspect Todo usage for this workspace.",
      "resetDatePrefix": "Usage resets",
      "sectionDescription": "This generated product currently reuses the shared workspace plan surface.",
      "sectionTitle": "Todo plan & usage",
      "selectedPlanSuffix": "selected",
      "switchToPlanPrefix": "Switch to",
      "usageWindowPrefix": "Usage window"
    }
  }
} satisfies TodoProductDefinition;
